@startuml
skinparam linetype ortho

interface iMapa << interface >> {
  + ingresarGladiadores(List<Gladiador>, int): void
  + getLargo(): int
  + getAncho(): int
  + getCasillas(): List<iCasilla>
  + moverGladiador(Gladiador, int): void
  + enviarAMitad(Gladiador): void
}

class Mapa {
  - largo: int
  - ancho: int
  - casillas: List<iCasilla>
  - casillaMedio: iCasilla
  - casillaUltima: iCasilla
  - EncontrarGladiador(Gladiador): iCasilla
  + Mapa(int, int):
  + agregarCamino(List<iCasilla>): void
  + ingresarGladiadores(List<Gladiador>, int): void
  + moverGladiador(Gladiador, int): void
  + enviarAMitad(Gladiador): void
  + getAncho(): int
  + getLargo(): int
  + getCasillas(): List<iCasilla>
}

interface iCasilla << interface >> {
  + validarPosicionEnCamino(int, int): void
  + getCoordenada(): Coordenada
  + recibir(Gladiador): void
  + expulsar(Gladiador): void
  + getGladiadores(): List<Gladiador>
  + esContigua(iCasilla): boolean
  + esContigua(Coordenada): boolean
  + getPremio(): Premio
  + buscadoEstaEnLaCasilla(Gladiador): iCasilla
  + getObstaculo(): Obstaculo
  + moverGladiador(int, Gladiador): void
  + setSiguiente(iCasilla): void
  + agregarObserver(Observer): void
}

iMapa <|.- Mapa
Mapa .> Gladiador
Mapa o-- "3..*"iCasilla


@enduml