@startuml
skinparam linetype ortho

class GestorTurnos {
  + GestorTurnos(int, ArrayList<Jugador>):
  - contador: int
  - cantidadRondas: int
  - colaTurnos: Queue<Jugador>
  + agregarTurno(Jugador): void
  + determinarPrimerJugador(): void
  + siguienteTurno(): void
}

class Dado {
  + Dado(int):
  + Dado():
  - caras: int
  - random: Random
  + lanzar(): int
}
GestorTurnos .-> Dado: "«create»  "
@enduml
