@startuml

skinparam linetype ortho

class Armadura {
  + Armadura(Gladiador, int):
  + mejorarEquipamiento(): void
}
class Casco {
  + Casco(Gladiador, int):
  + mejorarEquipamiento(): void
}
class Desnudo {
  + Desnudo(Gladiador):
  + mejorarEquipamiento(): void
}
abstract class Equipamiento {
  + Equipamiento():
  + gladiador: Gladiador
  + reduccionDeDanio: int
  + abrirCasaPompeya(): void
  + mejorarEquipamiento(): void
  + mitigarDanio(int): void
}
class EscudoEspada {
  + EscudoEspada(Gladiador, int):
  + mejorarEquipamiento(): void
}
class Llave {
  + Llave(Gladiador, int):
  + mejorarEquipamiento(): void
  + abrirCasaPompeya(): void
}

Equipamiento ^-- Armadura
Equipamiento ^-- Casco
Equipamiento ^-- Desnudo
Equipamiento ^-- EscudoEspada
Equipamiento ^- Llave

Desnudo .-> Casco : "«create»"
Casco .-> Armadura: "«create»"
Armadura .-> EscudoEspada: "«create»"
EscudoEspada .-> Llave: "«create»"

@enduml