@startuml
skinparam linetype ortho

class Mapa {
  - Mapa():
  - casillaMedio: Casilla
  - instancia: Mapa
  - primerCasilla: Casilla
  + getMapa(): Mapa
  + getMitadDeCamino(): Casilla
  + getPrimeraCasilla(): Casilla
}

@enduml
