@startuml
class Casilla {
    - iCasilla CasillaSiguiente
    + Casilla(coordenada: Coordenada, iCasilla CasillaSiguiente, premio:Premio,obstaculo:Obstaculo)
    + recibir(gladiador:Gladiador)
    + expulsar(gladiador:Gladiador)
    + otorgarPremio(gladiador:Gladiador)
    + aplicarObstaculo(gladiador:Gladiado)
}
@enduml