@startuml
skinparam linetype ortho

class Bacanal {
  + Bacanal():
  - representacion: char
  # perdidaEnergiaMinima: int
  + getRepresentacion(): char
  + obstaculizarGladiador(Gladiador): void
}

@enduml
