@startuml
skinparam linetype ortho

class FieraSalvaje {
  + FieraSalvaje():
  - danioDeFiera: int
  - representacion: char
  + getRepresentacion(): char
  + obstaculizarGladiador(Gladiador): void
}

@enduml
