@startuml
skinparam linetype ortho

class CasillaCamino {
  + CasillaCamino(Coordenada, iCasilla, Obstaculo, Premio):
  - coordenada: Coordenada
  - casillaSiguiente: iCasilla
  - obstaculo: Obstaculo
  - gladiadoresEnLaCasilla: List<Gladiador>
  - premio: Premio
  + buscadoEstaEnLaCasilla(Gladiador): iCasilla
  + recibir(Gladiador): void
  + getGladiadores(): List<Gladiador>
  + expulsar(Gladiador): void
  + getObstaculo(): Obstaculo
  + setSiguiente(iCasilla): void
  + getPremio(): Premio
  + moverGladiador(int, Gladiador): void
  + esContigua(Coordenada): boolean
  + esContigua(iCasilla): boolean
  + agregarObserver(Observer): void
  + validarPosicionEnCamino(int, int): void
  + getCoordenada(): Coordenada
}

@enduml
