@startuml
skinparam linetype ortho

class PremioComestible {
  + PremioComestible():
  - representacion: char
  - energiaParaEntregar: int
  + getRepresentacion(): char
  + premiarGladiador(Gladiador): void
}

@enduml
