@startuml
skinparam linetype ortho

class GladiadorSinEnergia {
  + GladiadorSinEnergia():
  - representacion: String
  + avanzar(Gladiador, iCasilla, int): void
  + getRepresentacion(): String
}

@enduml
