@startuml

skinparam linetype ortho

class GladiadorLesionado {
  + GladiadorLesionado():
  - representacion: String
  + avanzar(Gladiador, iCasilla, int): void
  + getRepresentacion(): String
}

@enduml
