@startuml
!include interfaz_estado.plantuml
!include clase_estado.plantuml
!include clase_conEnergia.plantuml
!include clase_sinEnergia.plantuml
!include clase_lesionado.plantuml

Estado <|-. GladiadorSano
Estado <|-. GladiadorSinEnergia
Estado <|-. GladiadorLesionado
@enduml