@startuml

skinparam linetype ortho

interface ISeniority << interface >> {
  + actualizar(): void
  + recuperarEnergia(): int
}
Abstract class NivelDeSeniority {
  + NivelDeSeniority():
  + actualizar(): NivelDeSeniority
  + recuperarEnergiaEnTurno(): int
}
class Novato {
  + Novato():
  + actualizar(): NivelDeSeniority
}
class SemiSenior {
  + SemiSenior():
  + actualizar(): NivelDeSeniority
}
class Senior {
  + Senior():
  + actualizar(): NivelDeSeniority
}
class Seniority {
  + Seniority():
  + actualizar(): void
  + recuperarEnergia(): int
}

NivelDeSeniority ^-- Novato
NivelDeSeniority ^-- SemiSenior
NivelDeSeniority ^-- Senior
ISeniority  ^-.   Seniority
Seniority o-- NivelDeSeniority
@enduml
