@startuml
class Juego {
    - jugadores:ArrayList<Jugador>
    - cantJugadores:int
    - {static}instancia: Juego
    - Juego(Mapa mapa, List<Jugador> jugadores):Juego
    - jugadoresValidos(jugadores:Jugador):bool
    + instanciarJuego(Mapa mapa, List<Jugador> jugadores):Juego
    - iniciarPartida()
    - moverGladiadorAMitadMapa(Gladiador gladiador)
    - buscarGanador()
    + {static}gladiadorSinLlaveLlegaAlFinal(Gladiador gladiador)
    + {static} gladiadorConLlaveLlegaAlFinal()

}
@enduml