@startuml
class Mapa {
    - casillas: List<Casilla>
    - casillaMedio: Casilla
    - casillaUltima: Casilla
    + Mapa(List<Gladiador> gladiadores, List<Casilla> casillas, int CantJugadores)
    - EncontrarGladiador(gladiador:Gladiador):Casilla
    + moverGladiador(Gladiador gladiador, int tiradaDeDado)
    + enviarAMitad(Gladiador gladiador)
}
@enduml