@startuml
skinparam linetype ortho

class Juego {
  - {static}instancia: Juego
  - Juego(iMapa, iDado, iGestorTurno):
  - jugadorActual: iJugador
  - ganador: iJugador
  + {static}instanciarJuego(iMapa, iDado, iGestorTurno): Juego
  + tirarDado(): iJugador
  + siguienteTurno(): void
  - buscarGanador(): void
  - moverGladiadorAMitadMapa(Gladiador): void
  + {static}gladiadorSinLlaveLlegaAlFinal(Gladiador gladiador)
  + {static} gladiadorConLlaveLlegaAlFinal()
  + {static} resetInstancia()
  + getJugadorActual(): iJugador
  + getGanador(): iJugador
}
@enduml

abstract class Observable {
  + Observable():
  + notifyObservers(Object): void
  + deleteObserver(Observer): void
  + countObservers(): int
  + notifyObservers(): void
  # setChanged(): void
  + deleteObservers(): void
  + hasChanged(): boolean
  + addObserver(Observer): void
  # clearChanged(): void
}

Juego       --^  Observable
