@startuml
skinparam linetype ortho

class Mapa {
  + Mapa(int, int):
  - ancho: int
  - casillaMedio: iCasilla
  - casillaUltima: iCasilla
  - largo: int
  - casillas: List<iCasilla>
  + ingresarGladiadores(List<Gladiador>, int): void
  - EncontrarGladiador(Gladiador): iCasilla
  + moverGladiador(Gladiador, int): void
  + enviarAMitad(Gladiador): void
  + agregarCamino(List<iCasilla>): void
  + getAncho(): int
  + getLargo(): int
  + getCasillas(): List<iCasilla>
}

@enduml
