@startuml

skinparam linetype ortho

class Jugador {
  + Jugador(String, int):
  - MiGladiador: Gladiador
  - miNombre: String
  + getGladiador(): Gladiador
  + getNombre(): String
  + jugar(iDado, iMapa): void
}

@enduml
