@startuml
class Parser {

    - anchoMapa : Int
    - largoMapa : Int
    - casillaAnterior : iCasilla
    + parsearJSON(nombreJSON: String) : List<iCasilla>
    - construirCasillaDesdeJSON(celdaJsonString: String): iCasilla
    - validarListaCasillas(casillas: List<iCasilla>)
    - obtenerValorNumerico(json: String, clave: String): int
    - obtenerValorString(json: String, clave: String): String
    - obtenerPremioPorString(stringPremio: String): Premio
    - obtenerObstaculoPorString(stringObstaculo: String): Obstaculo
    - obtenerDimensionesMapa(stringParteMapa: String)
     - validarCoordenadaCasilla(coordenada: Coordenada)


}
@enduml