@startuml


class Log {
  - mensajeAImprimir:String
  - construirLogger(): void
  + obtenerLogger(): Logger
  + imprimirMensaje(): void
  + agregarABuffer(String): void
   - instancia: Log

}

Log <-. Gladiador
Log <-. Novato
Log <-. SemiSenior
Juego .-> Log
Jugador .-> Log
Log <-. Desnudo
Log <-. Casco
Log <-. Armadura
Log <-. EscudoEspada
@enduml
// podemos incluir esto pero complejiza lo que se quiere mostrar sin aportar mucho mas
