@startuml
skinparam linetype ortho

abstract class Equipable {
  + Equipable():
  + mejorar(): Equipable
  + abrirCasaPompeya(Gladiador): void
  + mitigarDanio(int): int
   representacion: String
}

@enduml
