@startuml

skinparam linetype ortho

class Llave {
  + Llave(int):
  - representacion: String
  + abrirCasaPompeya(Gladiador): void
  + mejorar(): Equipable
  + getRepresentacion(): String
}

@enduml
