@startuml
!include ../variables.txt
skinparam Style strictuml
skinparam sequenceMessageAlign center
title caso de uso Parser\n

actor Actor #273746
participant ":Parser" #D5D8DC

Actor -> ":Parser" : parsearJSON(nombreJSON)
activate ":Parser" #D5D8DC
":Parser" -> ":Parser" : abrirJSON()
":Parser" --> "casillas: List<iCasilla>" ** : <<create>>
":Parser" -> ":Parser" : splitJSON()
":Parser" -> ":Parser" : obtenerDimensionesMapa()

loop cantidad de celdas

    ":Parser" -> ":Parser" : obtenerSiguienteCelda(): String celda
    ":Parser" -> ":Parser" : validar(celda)
    ":Parser" --> "nuevaCasilla:iCasilla" ** : <<create>>
    activate "casillas: List<iCasilla>" #D5D8DC
    ":Parser" -> "casillas: List<iCasilla>" : add(nuevaCasilla)
end

loop cantidad de casillas

    ":Parser" -> "casillas: List<iCasilla>" : getCasilla(i)
    "casillas: List<iCasilla>" -->  ":Parser" : casilla: iCasilla

    ":Parser" -> ":Parser" : validar(casilla)


end

":Parser" --> Actor : casillas

@enduml
