@startuml

actor Actor
participant ":Juego"
participant ":GestorTurnos"
participant ":Dado"
Actor -> ":Juego" ** : instanciarJuego(mapa: Mapa, jugadores: List<Jugador>)
activate ":Juego"
":Juego" -> ":GestorTurnos"**: new ":GestorTurnos"(rondas = 30, jugadores)

activate ":GestorTurnos"
":GestorTurnos" --> ":Juego": :GestorTurnos
deactivate ":GestorTurnos"


":Juego" -> ":Dado"**: new ":Dado"()
activate ":Dado"
":Dado" --> ":Juego":
deactivate ":Dado"
":Juego" --> Actor: instancia: ":Juego"

deactivate ":Juego"

@enduml