@startuml JugadorSaleDeLaCasillaInicial

skinparam guillemet none
autoactivate on

actor test02
autoactivate on

participant Mapa as M << C >>
participant Mapa as m << mapa : >>
participant EventoNulo as eAburrido << eventoAburrido : >>
participant EventoEquipamiento as eEquipo << eventoEquipo : >>
participant EventoPompeya as ePompeya << eventoPompeya : >>
participant Casilla as c1 << casillaInicial : >>
participant Casilla as c2 << casillaMedio : >>
participant Casilla as c3 << casillaFinal : >>

participant Gladiador as g << g : >>
participant Novato as novato << seniority : >>
participant GladiadorSano as sano << estado : >>
participant Desnudo as desnudo << equipamiento : >>

test02 -> M : getMapa()
M -> m ** : new Mapa()
m -> eAburrido ** : new EventoNulo()
m -> eEquipo ** : new EventoEquipo()
m -> ePompeya ** : new EventoPompeya()
m -> c1 ** : new Casilla(casillaMedio, eventoAburrido)
m -> c2 ** : new Casilla(casillaFinal, eventoEquipo)
m -> c3 ** : new Casilla(null, eventoPompeya)
M --> test02 : mapa

test02 -> g ** : new Gladiador(casillaInicial)
g -> desnudo ** : new Desnudo()
g -> sano ** : new GladiadorSano()
g -> novato ** : new Novato()

test02 -> m : getPrimeraCasilla()
m --> test02 : casillaInicial

test02 -> g : getCasilla()
g --> test02 : casillaInicial


@enduml