@startuml
!include clases/clase_juego.plantuml
!include clases/clase_gestorTurnos.plantuml
!include clases/clase_jugador.plantuml
!include clases/clase_mapa.plantuml
!include clases/parser/clase_parser.plantuml

!include clases/clase_gladiador.plantuml
!include clases/clase_dado.plantuml

!include clases/seniority/diagrama_seniority.plantuml
!include clases/equipamiento/diagrama_equipamiento_actual.plantuml
!include clases/estado/diagrama_estado.plantuml
!include clases/casilla/diagrama_casilla.plantuml

class CasillaInicio {
    - iCasilla CasillaSiguiente
    + Casilla(coordenada: Coordenada, iCasilla CasillaSiguiente)
    + recibir(gladiador:Gladiador)
    + expulsar(gladiador:Gladiador)
}
class CasillaFinal {
    - iCasilla CasillaSiguiente
    + Casilla(coordenada: Coordenada, iCasilla CasillaSiguiente)
    + recibir(gladiador:Gladiador)
    + expulsar(gladiador:Gladiador)
}

class Log {
  - mensajeAImprimir:String
  - {static} construirLogger(): void
  + {static} obtenerLogger(): Logger
  + {static} getLog()
  + imprimirMensaje(): void
  + agregarABuffer(String): void
   - instancia: Log
}

class LogFormatter {
  + LogFormatter():
  - calcularFecha(long): String
  + format(LogRecord): String
}

Log .>  LogFormatter

interface iMapa << interface >> {
  + moverGladiador(Gladiador, int): void
  + enviarAMitad(Gladiador): void
}

interface iJugador << interface >> {
  + jugar(Dado, iMapa): void
}

interface iDado {
    public int lanzar();
}


iCasilla ^-. CasillaInicio
iCasilla ^-. CasillaFinal
Juego o-- iMapa
iMapa <|-. Mapa
Mapa .-> Gladiador
Juego o-- GestorTurnos
Juego o-- iDado
iDado <|. Dado
GestorTurnos o-- "2..6 " iJugador
iJugador <|-. Jugador
Jugador *-- Gladiador
Jugador ..> iDado
Jugador ..> Mapa

Mapa o-- "2..*"iCasilla
iCasilla o- "0..6 " Gladiador

Gladiador o-- ISeniority
Gladiador o- IEquipamiento
Gladiador o-- IEstado

Parser .--> iCasilla


interface ISeniority <<interface>> {
}

interface IEstado <<interface>> {
}

interface IEquipamiento <<interface>> {

}

@enduml
